version: "3.4"
services:
    nopcommerce_web:
        build: .
        container_name: nopcommerce
        ports:
            - "8080:80"
        volumes:
          - ./App_Data/AppSettings:/app/App_Data/AppSettings
          - ./App_Data/DataProtectionKeys:/app/App_Data/DataProtectionKeys
        depends_on:
            - nopcommerce_database
        restart: "always"
    nopcommerce_database:
        image: "postgres:latest"
        container_name: nopcommerce_postgres_server
        restart: "always"
        environment:
          POSTGRES_PASSWORD: "nopCommerce_db_password"
        volumes:
          - ./App_Data/postgres:/var/lib/postgresql/data

volumes:
  nopcommerce_data: